name: Deploy to Hugging Face

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 11:00 AM Pakistan Time
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git identity
      run: |
        git config --global user.email "mehnoorfayyaz06@gmail.com"
        git config --global user.name "Menoor00"

    - name: Push to Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git remote add hf https://${HF_TOKEN}@huggingface.co/spaces/Mehnoor00/AQI_Webapp
        git push hf master:main --force
