name: Deploy to Hugging Face

on:
  schedule:
    - cron:  "0 */3 * * *"  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git identity
      run: |
        git config --global user.email "mehnoorfayyaz06@gmail.com"
        git config --global user.name "Menoor00"

    - name: Push to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git config --global user.email "mehnoorfayyaz06@gmail.com"
        git config --global user.name "Mehnoor00"
        git remote add hf https://Mehnoor00:${HF_TOKEN}@huggingface.co/spaces/Mehnoor00/Lahore-AQI-Predictions
        git fetch --unshallow
        git push hf master:main --force
