name: Deploy to Hugging Face

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 11:00 AM PKT (6 AM UTC)
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git identity
      run: |
        git config --global user.email "mehnoorfayyaz06@gmail.com"
        git config --global user.name "ManoFayyaz"

    - name: Ensure commit exists
      run: |
        if [ -z "$(git rev-parse --verify HEAD 2>/dev/null)" ]; then
          git checkout -b main
          git commit --allow-empty -m "Initial commit"
        fi

    - name: Push to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git remote add hf https://huggingface.co/spaces/Mehnoor00/AQI_Webapp
        git push hf main --force
