name: AQI Feature Store Pipeline

on:
  schedule:
     - cron: '10 5 * * *'  # Runs daily at 10:10 AM PKT
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  update-feature-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
            pip install pandas "hopsworks[python]"

      - name: Upload to Feature Store
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY}}
        run: python feature_group.py
        
      #- name: Feature View
      #  env:
          #    HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY}}
        #run: python feature_view.py
        
      - name: Create Training Dataset
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: python training_data.py

      - name: 📥 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  --no-cache-dir -r requirements.txt

      - name: Train and Register Model
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: python train_models.py
              
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
